INFO 2025-07-25 10:00:18,454 autoreload 12 137194695895936 Watching for file changes with StatReloader
INFO 2025-07-25 10:01:17,491 autoreload 19452 14908 Watching for file changes with StatReloader
INFO 2025-07-25 10:03:36,578 autoreload 26340 16900 Watching for file changes with StatReloader
INFO 2025-07-25 10:15:42,992 autoreload 19 134246440983424 Watching for file changes with StatReloader
INFO 2025-07-25 10:16:54,888 basehttp 19 134245752927936 "GET /admin/users/user/ HTTP/1.1" 302 0
INFO 2025-07-25 10:16:54,918 basehttp 19 134245752927936 "GET /admin/login/?next=/admin/users/user/ HTTP/1.1" 200 4259
INFO 2025-07-25 10:17:03,241 basehttp 19 134245733168832 "GET / HTTP/1.1" 302 0
ERROR 2025-07-25 10:17:03,299 log 19 134245733168832 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/patients/views.py", line 106, in get_context_data
    diabetic_patients = Patient.objects.filter(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1503, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:17:03,311 basehttp 19 134245733168832 "GET /patients/ HTTP/1.1" 500 137660
INFO 2025-07-25 10:20:09,540 autoreload 19 134246440983424 /app/patients/views.py changed, reloading.
INFO 2025-07-25 10:20:10,050 autoreload 66 128130214148992 Watching for file changes with StatReloader
INFO 2025-07-25 10:20:23,638 autoreload 66 128130214148992 /app/patients/views.py changed, reloading.
INFO 2025-07-25 10:20:24,093 autoreload 79 130333473180544 Watching for file changes with StatReloader
INFO 2025-07-25 10:20:28,160 basehttp 79 130332785194688 "GET / HTTP/1.1" 302 0
ERROR 2025-07-25 10:20:28,212 log 79 130332785194688 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/patients/views.py", line 106, in get_context_data
    diabetic_patients = Patient.objects.filter(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1503, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:20:28,221 basehttp 79 130332785194688 "GET /patients/ HTTP/1.1" 500 137797
ERROR 2025-07-25 10:20:39,649 log 79 130332785194688 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/patients/views.py", line 106, in get_context_data
    diabetic_patients = Patient.objects.filter(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1503, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:20:39,653 basehttp 79 130332785194688 "GET /patients/ HTTP/1.1" 500 137797
INFO 2025-07-25 10:32:56,449 autoreload 79 130333473180544 /app/patients/views.py changed, reloading.
INFO 2025-07-25 10:32:57,343 autoreload 94 133857956543360 Watching for file changes with StatReloader
ERROR 2025-07-25 10:33:04,226 log 94 133857268569792 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: patients/patient_list.html, patients/patient_list.html
ERROR 2025-07-25 10:33:04,227 basehttp 94 133857268569792 "GET /patients/ HTTP/1.1" 500 75566
INFO 2025-07-25 10:33:43,744 autoreload 94 133857956543360 /app/localscore/settings.py changed, reloading.
INFO 2025-07-25 10:33:44,305 autoreload 109 135398785915776 Watching for file changes with StatReloader
INFO 2025-07-25 10:33:46,018 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 200 24343
ERROR 2025-07-25 10:33:51,945 log 109 135398097946304 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 10:33:51,956 basehttp 109 135398097946304 "GET /score2/stats/ HTTP/1.1" 500 271827
INFO 2025-07-25 10:34:04,316 basehttp 109 135398097946304 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 10:34:12,648 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 10:34:16,469 basehttp 109 135398097946304 "GET /patients/?search=&diabetes=&age=&score_status= HTTP/1.1" 200 24343
INFO 2025-07-25 10:34:18,825 basehttp 109 135398097946304 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 10:34:47,957 basehttp 109 135398097946304 "POST /patients/import/ HTTP/1.1" 200 31769
INFO 2025-07-25 10:34:56,170 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 10:34:57,146 basehttp 109 135398097946304 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 10:36:09,550 basehttp 109 135398097946304 "POST /patients/import/ HTTP/1.1" 302 0
ERROR 2025-07-25 10:36:09,634 log 109 135398097946304 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/app/patients/models.py", line 54, in has_diabetes
    chronic_diabetes = self.chronic_diagnoses.filter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:36:09,646 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 500 291977
ERROR 2025-07-25 10:36:59,547 log 109 135398097946304 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/app/patients/models.py", line 54, in has_diabetes
    chronic_diabetes = self.chronic_diagnoses.filter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:36:59,552 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 500 291923
ERROR 2025-07-25 10:37:06,246 log 109 135398097946304 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/app/patients/models.py", line 54, in has_diabetes
    chronic_diabetes = self.chronic_diagnoses.filter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:37:06,253 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 500 292060
INFO 2025-07-25 10:37:12,202 basehttp 109 135398097946304 "GET /patients/import/ HTTP/1.1" 200 30551
ERROR 2025-07-25 10:37:14,128 log 109 135398097946304 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/app/patients/models.py", line 54, in has_diabetes
    chronic_diabetes = self.chronic_diagnoses.filter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 10:37:14,133 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 500 291923
ERROR 2025-07-25 11:16:10,300 log 109 135398097946304 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/app/patients/models.py", line 54, in has_diabetes
    chronic_diabetes = self.chronic_diagnoses.filter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1402, in build_lookup
    lhs = self.try_transform(lhs, name, lookups)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1458, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'startswith__in' for CharField or join on the field not permitted, perhaps you meant startswith or istartswith?
ERROR 2025-07-25 11:16:10,304 basehttp 109 135398097946304 "GET /patients/ HTTP/1.1" 500 291756
INFO 2025-07-25 11:20:48,240 autoreload 109 135398785915776 /app/patients/models.py changed, reloading.
INFO 2025-07-25 11:20:49,254 autoreload 129 128171364191104 Watching for file changes with StatReloader
ERROR 2025-07-25 11:20:53,291 log 129 128170676082368 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 320, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 722, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 925, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/app/patients/models.py", line 52, in has_diabetes
    q = Q()
        ^
NameError: name 'Q' is not defined
ERROR 2025-07-25 11:20:53,307 basehttp 129 128170676082368 "GET /patients/ HTTP/1.1" 500 243231
INFO 2025-07-25 11:22:16,491 autoreload 129 128171364191104 /app/patients/models.py changed, reloading.
INFO 2025-07-25 11:22:17,232 autoreload 144 124004778654592 Watching for file changes with StatReloader
INFO 2025-07-25 11:22:22,294 autoreload 144 124004778654592 /app/patients/models.py changed, reloading.
INFO 2025-07-25 11:22:22,823 autoreload 157 130668175022976 Watching for file changes with StatReloader
INFO 2025-07-25 11:22:28,788 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 84467
INFO 2025-07-25 11:22:35,003 basehttp 157 130667486914240 "GET /patients/?page=2 HTTP/1.1" 200 85789
ERROR 2025-07-25 11:22:42,285 log 157 130667486914240 Internal Server Error: /patients/251/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':visit_info.visit.visit_date' from 'patient.calculate_age:visit_info.visit.visit_date'
ERROR 2025-07-25 11:22:42,288 basehttp 157 130667486914240 "GET /patients/251/ HTTP/1.1" 500 319475
INFO 2025-07-25 11:22:49,642 basehttp 157 130667486914240 "GET /patients/?page=3 HTTP/1.1" 200 87198
INFO 2025-07-25 11:23:01,411 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:23:08,815 basehttp 157 130667486914240 "GET /patients/?page=4 HTTP/1.1" 200 86117
INFO 2025-07-25 11:23:11,237 basehttp 157 130667486914240 "GET /patients/?page=5 HTTP/1.1" 200 86128
INFO 2025-07-25 11:23:25,069 basehttp 157 130667486914240 "POST /score2/calculate-all/ HTTP/1.1" 200 134
INFO 2025-07-25 11:23:27,158 basehttp 157 130667486914240 "GET /patients/?page=5 HTTP/1.1" 200 86129
INFO 2025-07-25 11:23:32,930 basehttp 157 130667486914240 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 80796
ERROR 2025-07-25 11:23:47,141 log 157 130667486914240 Internal Server Error: /patients/92/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':visit_info.visit.visit_date' from 'patient.calculate_age:visit_info.visit.visit_date'
ERROR 2025-07-25 11:23:47,144 basehttp 157 130667486914240 "GET /patients/92/ HTTP/1.1" 500 319517
INFO 2025-07-25 11:24:42,255 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:24:43,479 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:24:43,792 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:24:43,978 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:24:44,162 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:24:51,097 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:25:07,310 basehttp 157 130667486914240 "GET /patients/?search=64120606296&diabetes=&age=&score_status=calculated HTTP/1.1" 200 28988
INFO 2025-07-25 11:25:11,511 basehttp 157 130667486914240 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:25:17,663 basehttp 157 130667486914240 "POST /patients/import/ HTTP/1.1" 302 0
INFO 2025-07-25 11:25:17,737 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 85575
INFO 2025-07-25 11:25:19,827 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 84468
INFO 2025-07-25 11:25:25,577 basehttp 157 130667486914240 "POST /score2/calculate-all/ HTTP/1.1" 200 134
INFO 2025-07-25 11:25:27,707 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 84468
ERROR 2025-07-25 11:26:04,930 log 157 130667486914240 Internal Server Error: /patients/267/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':visit_info.visit.visit_date' from 'patient.calculate_age:visit_info.visit.visit_date'
ERROR 2025-07-25 11:26:04,932 basehttp 157 130667486914240 "GET /patients/267/ HTTP/1.1" 500 319468
INFO 2025-07-25 11:26:12,836 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 84468
ERROR 2025-07-25 11:26:14,198 log 157 130667486914240 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 11:26:14,206 basehttp 157 130667486914240 "GET /score2/stats/ HTTP/1.1" 500 274558
INFO 2025-07-25 11:26:16,475 basehttp 157 130667486914240 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:26:29,643 basehttp 157 130667486914240 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:26:33,438 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 84468
INFO 2025-07-25 11:28:19,944 basehttp 157 130667486914240 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 80822
INFO 2025-07-25 11:28:31,857 basehttp 157 130667486914240 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:28:35,384 basehttp 157 130667486914240 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 80822
INFO 2025-07-25 11:32:22,702 basehttp 157 130667486914240 "GET / HTTP/1.1" 302 0
INFO 2025-07-25 11:32:22,781 basehttp 157 130667486914240 "GET /patients/ HTTP/1.1" 200 84468
INFO 2025-07-25 11:32:26,370 basehttp 157 130667486914240 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-07-25 11:32:26,440 basehttp 157 130667486914240 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4237
INFO 2025-07-25 11:32:26,452 basehttp 157 130667478521536 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-07-25 11:32:26,453 basehttp 157 130667486914240 "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-07-25 11:32:26,454 basehttp 157 130667391219392 "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-07-25 11:32:26,468 basehttp 157 130667486914240 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-07-25 11:32:26,468 basehttp 157 130667391219392 "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-07-25 11:32:26,468 basehttp 157 130667478521536 "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-07-25 11:32:26,487 basehttp 157 130667486914240 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-07-25 11:32:29,354 basehttp 157 130667391219392 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-07-25 11:32:29,387 basehttp 157 130667391219392 "GET /admin/ HTTP/1.1" 200 10939
INFO 2025-07-25 11:32:29,416 basehttp 157 130667391219392 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-07-25 11:32:29,417 basehttp 157 130667478521536 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-07-25 11:32:29,418 basehttp 157 130667486914240 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-07-25 11:32:35,462 basehttp 157 130667391219392 "GET /admin/patients/visit/ HTTP/1.1" 200 25118
INFO 2025-07-25 11:32:35,498 basehttp 157 130667478521536 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-07-25 11:32:35,500 basehttp 157 130667374433984 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-07-25 11:32:35,501 basehttp 157 130667486914240 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-07-25 11:32:35,505 basehttp 157 130667366041280 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-07-25 11:32:35,509 basehttp 157 130667374433984 "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-07-25 11:32:35,509 basehttp 157 130667478521536 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-07-25 11:32:35,513 basehttp 157 130667486914240 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-07-25 11:32:35,517 basehttp 157 130667391219392 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:32:35,518 basehttp 157 130667478521536 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-07-25 11:32:35,519 basehttp 157 130667382826688 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-07-25 11:32:35,521 basehttp 157 130667366041280 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-07-25 11:32:35,531 basehttp 157 130667366041280 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-07-25 11:32:35,541 basehttp 157 130667391219392 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-07-25 11:32:35,542 basehttp 157 130667486914240 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-07-25 11:32:35,542 basehttp 157 130667382826688 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-07-25 11:32:43,945 basehttp 157 130667391219392 "GET /admin/score2/score2result/ HTTP/1.1" 200 38374
INFO 2025-07-25 11:32:43,971 basehttp 157 130667391219392 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:33:02,811 basehttp 157 130667391219392 "GET /admin/patients/patient/ HTTP/1.1" 200 82199
INFO 2025-07-25 11:33:02,840 basehttp 157 130667391219392 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:33:11,771 basehttp 157 130667391219392 "GET /admin/patients/visitdiagnosis/ HTTP/1.1" 200 58324
INFO 2025-07-25 11:33:11,799 basehttp 157 130667391219392 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:33:32,356 basehttp 157 130667391219392 "GET /admin/patients/visit/ HTTP/1.1" 200 25118
INFO 2025-07-25 11:33:32,384 basehttp 157 130667391219392 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:36:06,404 autoreload 157 130668175022976 /app/patients/views.py changed, reloading.
INFO 2025-07-25 11:36:06,927 autoreload 197 128647517047680 Watching for file changes with StatReloader
ERROR 2025-07-25 11:36:11,644 log 197 128646829090496 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 11:36:11,651 basehttp 197 128646829090496 "GET /score2/stats/ HTTP/1.1" 500 274758
INFO 2025-07-25 11:36:13,577 basehttp 197 128646829090496 "GET /patients/ HTTP/1.1" 200 84468
ERROR 2025-07-25 11:36:15,690 log 197 128646829090496 Internal Server Error: /patients/271/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':visit_info.visit.visit_date' from 'patient.calculate_age:visit_info.visit.visit_date'
ERROR 2025-07-25 11:36:15,693 basehttp 197 128646829090496 "GET /patients/271/ HTTP/1.1" 500 319609
INFO 2025-07-25 11:36:59,474 basehttp 197 128646829090496 "GET /patients/271/ HTTP/1.1" 200 26065
INFO 2025-07-25 11:37:07,373 basehttp 197 128646829090496 "GET /patients/ HTTP/1.1" 200 84468
INFO 2025-07-25 11:37:11,222 basehttp 197 128646829090496 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 80822
INFO 2025-07-25 11:37:13,093 basehttp 197 128646829090496 "GET /patients/215/ HTTP/1.1" 200 40761
INFO 2025-07-25 11:38:33,012 basehttp 197 128646829090496 "POST /score2/calculate/215/ HTTP/1.1" 200 105
INFO 2025-07-25 11:38:39,875 basehttp 197 128646829090496 "GET /patients/ HTTP/1.1" 200 84468
INFO 2025-07-25 11:41:12,697 autoreload 197 128647517047680 /app/patients/views.py changed, reloading.
INFO 2025-07-25 11:41:13,222 autoreload 214 138574248217472 Watching for file changes with StatReloader
INFO 2025-07-25 11:41:17,073 basehttp 214 138573560260288 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:41:25,909 basehttp 214 138573560260288 "POST /patients/import/ HTTP/1.1" 302 0
INFO 2025-07-25 11:41:26,030 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 107262
INFO 2025-07-25 11:41:28,143 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 106150
INFO 2025-07-25 11:41:33,952 basehttp 214 138573560260288 "POST /score2/calculate-all/ HTTP/1.1" 200 137
INFO 2025-07-25 11:41:36,096 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 114911
INFO 2025-07-25 11:41:40,315 basehttp 214 138573560260288 "GET /patients/269/ HTTP/1.1" 200 38380
INFO 2025-07-25 11:41:51,195 basehttp 214 138573560260288 "GET /patients/258/ HTTP/1.1" 200 38219
INFO 2025-07-25 11:41:56,897 basehttp 214 138573560260288 "GET /patients/?page=2 HTTP/1.1" 200 116233
INFO 2025-07-25 11:42:00,325 basehttp 214 138573560260288 "GET /patients/249/ HTTP/1.1" 200 37765
INFO 2025-07-25 11:42:03,905 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 114911
INFO 2025-07-25 11:43:09,302 basehttp 214 138573560260288 "GET /patients/272/ HTTP/1.1" 200 38809
INFO 2025-07-25 11:43:26,687 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 115107
INFO 2025-07-25 11:43:33,889 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 115107
INFO 2025-07-25 11:43:36,894 basehttp 214 138573560260288 "GET /patients/272/ HTTP/1.1" 200 38809
INFO 2025-07-25 11:43:53,625 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=2 HTTP/1.1" 200 116570
INFO 2025-07-25 11:43:56,138 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=3 HTTP/1.1" 200 116939
INFO 2025-07-25 11:44:00,942 basehttp 214 138573560260288 "GET /patients/215/ HTTP/1.1" 200 42773
INFO 2025-07-25 11:44:06,996 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=4 HTTP/1.1" 200 116940
INFO 2025-07-25 11:44:09,326 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=6 HTTP/1.1" 200 116965
INFO 2025-07-25 11:44:11,865 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=7 HTTP/1.1" 200 116969
INFO 2025-07-25 11:44:13,985 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=8 HTTP/1.1" 200 116949
INFO 2025-07-25 11:44:16,807 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=9 HTTP/1.1" 200 116924
INFO 2025-07-25 11:44:20,022 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=10 HTTP/1.1" 200 116927
INFO 2025-07-25 11:45:18,201 basehttp 214 138573560260288 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:45:34,317 basehttp 214 138573560260288 "POST /patients/import/ HTTP/1.1" 302 0
INFO 2025-07-25 11:45:34,442 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 116071
INFO 2025-07-25 11:45:36,574 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 114961
INFO 2025-07-25 11:46:08,919 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 114961
INFO 2025-07-25 11:46:31,866 basehttp 214 138573560260288 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:46:43,351 basehttp 214 138573560260288 "POST /patients/import/ HTTP/1.1" 302 0
INFO 2025-07-25 11:46:43,508 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 116069
INFO 2025-07-25 11:46:45,636 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 114961
INFO 2025-07-25 11:46:54,503 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 114961
INFO 2025-07-25 11:48:55,105 basehttp 214 138573560260288 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 11:49:24,535 basehttp 214 138573560260288 "POST /patients/import/ HTTP/1.1" 302 0
INFO 2025-07-25 11:49:24,707 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 102816
INFO 2025-07-25 11:49:26,839 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 101701
INFO 2025-07-25 11:49:42,837 basehttp 214 138573560260288 "POST /score2/calculate-all/ HTTP/1.1" 200 140
INFO 2025-07-25 11:49:45,027 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 110462
INFO 2025-07-25 11:50:15,358 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 110658
INFO 2025-07-25 11:50:20,144 basehttp 214 138573560260288 "GET /patients/1780/ HTTP/1.1" 200 37473
INFO 2025-07-25 11:50:29,955 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=2 HTTP/1.1" 200 112121
INFO 2025-07-25 11:50:32,116 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=3 HTTP/1.1" 200 112461
INFO 2025-07-25 11:50:34,489 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=4 HTTP/1.1" 200 113385
INFO 2025-07-25 11:50:36,970 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=5 HTTP/1.1" 200 112915
INFO 2025-07-25 11:50:47,397 basehttp 214 138573560260288 "GET /patients/?search=95041003712&diabetes=&age=&score_status=calculated HTTP/1.1" 200 28533
INFO 2025-07-25 11:50:52,826 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated HTTP/1.1" 200 110658
INFO 2025-07-25 11:50:55,228 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=3 HTTP/1.1" 200 112461
INFO 2025-07-25 11:50:59,412 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=4 HTTP/1.1" 200 113385
INFO 2025-07-25 11:51:02,357 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=5 HTTP/1.1" 200 112915
INFO 2025-07-25 11:51:04,714 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=6 HTTP/1.1" 200 112476
INFO 2025-07-25 11:51:07,162 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=7 HTTP/1.1" 200 112473
INFO 2025-07-25 11:51:09,424 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=8 HTTP/1.1" 200 112469
INFO 2025-07-25 11:51:11,520 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=9 HTTP/1.1" 200 112458
INFO 2025-07-25 11:51:13,564 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=10 HTTP/1.1" 200 112472
INFO 2025-07-25 11:51:15,917 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=11 HTTP/1.1" 200 112475
INFO 2025-07-25 11:51:18,383 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=12 HTTP/1.1" 200 112946
INFO 2025-07-25 11:51:26,638 basehttp 214 138573560260288 "GET /patients/272/ HTTP/1.1" 200 48533
INFO 2025-07-25 11:51:42,814 basehttp 214 138573560260288 "GET /patients/272/ HTTP/1.1" 200 48533
INFO 2025-07-25 11:51:54,212 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=13 HTTP/1.1" 200 112466
INFO 2025-07-25 11:51:56,755 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=14 HTTP/1.1" 200 112934
INFO 2025-07-25 11:52:00,357 basehttp 214 138573560260288 "GET /patients/271/ HTTP/1.1" 200 45172
INFO 2025-07-25 11:52:06,518 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=&score_status=calculated&page=15 HTTP/1.1" 200 112937
INFO 2025-07-25 11:52:13,980 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated HTTP/1.1" 200 106859
INFO 2025-07-25 11:52:20,797 basehttp 214 138573560260288 "GET /patients/248/ HTTP/1.1" 200 49830
INFO 2025-07-25 11:52:29,393 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated&page=2 HTTP/1.1" 200 108335
INFO 2025-07-25 11:52:33,322 basehttp 214 138573560260288 "GET /patients/245/ HTTP/1.1" 200 51711
INFO 2025-07-25 11:52:38,251 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated&page=3 HTTP/1.1" 200 108294
INFO 2025-07-25 11:52:40,999 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated&page=4 HTTP/1.1" 200 109669
INFO 2025-07-25 11:52:44,078 basehttp 214 138573560260288 "GET /patients/244/ HTTP/1.1" 200 48678
INFO 2025-07-25 11:52:49,974 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated&page=4 HTTP/1.1" 200 109669
INFO 2025-07-25 11:52:59,073 basehttp 214 138573560260288 "GET /patients/243/ HTTP/1.1" 200 49966
INFO 2025-07-25 11:53:16,815 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated&page=5 HTTP/1.1" 200 108714
INFO 2025-07-25 11:53:20,078 basehttp 214 138573560260288 "GET /patients/239/ HTTP/1.1" 200 49273
INFO 2025-07-25 11:53:43,187 basehttp 214 138573560260288 "GET /patients/?search=&diabetes=&age=50-59&score_status=calculated&page=6 HTTP/1.1" 200 109151
INFO 2025-07-25 11:53:48,737 basehttp 214 138573560260288 "GET /patients/238/ HTTP/1.1" 200 48416
INFO 2025-07-25 11:55:28,997 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 110462
ERROR 2025-07-25 11:55:30,050 log 214 138573560260288 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 11:55:30,059 basehttp 214 138573560260288 "GET /score2/stats/ HTTP/1.1" 500 276073
INFO 2025-07-25 11:55:41,589 basehttp 214 138573560260288 "GET /admin/patients/patient/ HTTP/1.1" 200 82605
INFO 2025-07-25 11:55:41,608 basehttp 214 138573560260288 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,610 basehttp 214 138573551867584 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,616 basehttp 214 138573518476992 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,617 basehttp 214 138573526869696 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,617 basehttp 214 138573160380096 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,617 basehttp 214 138573510084288 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,620 basehttp 214 138573518476992 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,621 basehttp 214 138573526869696 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,621 basehttp 214 138573510084288 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,622 basehttp 214 138573160380096 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,628 basehttp 214 138573551867584 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:55:41,631 basehttp 214 138573551867584 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,658 basehttp 214 138573560260288 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,663 basehttp 214 138573518476992 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,667 basehttp 214 138573526869696 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,668 basehttp 214 138573510084288 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,712 basehttp 214 138573526869696 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,712 basehttp 214 138573510084288 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,724 basehttp 214 138573560260288 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,724 basehttp 214 138573518476992 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,724 basehttp 214 138573551867584 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2025-07-25 11:55:41,726 basehttp 214 138573160380096 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-07-25 11:55:46,970 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 200 116576
INFO 2025-07-25 11:55:46,992 basehttp 214 138573560260288 "GET /static/admin/js/cancel.js HTTP/1.1" 200 884
INFO 2025-07-25 11:55:51,389 basehttp 214 138573560260288 "GET /admin/patients/patient/ HTTP/1.1" 200 82605
INFO 2025-07-25 11:55:51,415 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:56:11,553 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 200 116576
INFO 2025-07-25 11:56:19,928 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 302 0
INFO 2025-07-25 11:56:20,185 basehttp 214 138573560260288 "GET /admin/patients/patient/ HTTP/1.1" 200 82183
INFO 2025-07-25 11:56:20,216 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:56:20,228 basehttp 214 138573560260288 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-07-25 11:56:23,660 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 200 149939
INFO 2025-07-25 11:56:27,639 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 302 0
INFO 2025-07-25 11:56:27,907 basehttp 214 138573560260288 "GET /admin/patients/patient/ HTTP/1.1" 200 82291
INFO 2025-07-25 11:56:27,942 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:56:31,812 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 200 131973
INFO 2025-07-25 11:56:35,114 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 302 0
INFO 2025-07-25 11:56:35,384 basehttp 214 138573560260288 "GET /admin/patients/patient/ HTTP/1.1" 200 82483
INFO 2025-07-25 11:56:35,414 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:56:40,172 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 200 148252
INFO 2025-07-25 11:56:43,712 basehttp 214 138573560260288 "POST /admin/patients/patient/ HTTP/1.1" 302 0
INFO 2025-07-25 11:56:44,017 basehttp 214 138573560260288 "GET /admin/patients/patient/ HTTP/1.1" 200 82435
INFO 2025-07-25 11:56:44,049 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:56:59,062 basehttp 214 138573560260288 "GET /admin/patients/patient/?_facets=True HTTP/1.1" 200 86398
INFO 2025-07-25 11:56:59,088 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:56:59,102 basehttp 214 138573560260288 "GET /static/admin/img/icon-hidelink.svg HTTP/1.1" 200 784
INFO 2025-07-25 11:57:00,900 basehttp 214 138573560260288 "GET /admin/patients/patient/? HTTP/1.1" 200 82295
INFO 2025-07-25 11:57:00,932 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:57:01,730 basehttp 214 138573560260288 "GET /admin/patients/patient/?_facets=True HTTP/1.1" 200 86398
INFO 2025-07-25 11:57:01,759 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:57:02,767 basehttp 214 138573560260288 "GET /admin/patients/patient/? HTTP/1.1" 200 82295
INFO 2025-07-25 11:57:02,795 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:57:03,567 basehttp 214 138573560260288 "GET /admin/patients/patient/?_facets=True HTTP/1.1" 200 86398
INFO 2025-07-25 11:57:03,594 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 11:58:59,348 basehttp 214 138573560260288 "GET /patients/1768/ HTTP/1.1" 200 37323
INFO 2025-07-25 11:59:05,537 basehttp 214 138573560260288 "POST /score2/calculate/1767/ HTTP/1.1" 200 105
WARNING 2025-07-25 11:59:14,583 log 214 138573560260288 Not Found: /patients/1784/
WARNING 2025-07-25 11:59:14,584 basehttp 214 138573560260288 "GET /patients/1784/ HTTP/1.1" 404 3362
INFO 2025-07-25 11:59:21,319 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 109231
INFO 2025-07-25 12:02:18,837 basehttp 214 138573560260288 "GET /admin/patients/patient/?_facets=True HTTP/1.1" 200 14129
INFO 2025-07-25 12:02:18,865 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 12:02:20,292 basehttp 214 138573560260288 "GET /admin/patients/patientdiagnosis/ HTTP/1.1" 200 13766
INFO 2025-07-25 12:02:20,316 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 12:02:21,009 basehttp 214 138573560260288 "GET /admin/patients/diagnosis/ HTTP/1.1" 200 53511
INFO 2025-07-25 12:02:21,041 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 12:02:26,437 basehttp 214 138573560260288 "GET /admin/patients/visitdiagnosis/ HTTP/1.1" 200 13599
INFO 2025-07-25 12:02:26,465 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
INFO 2025-07-25 12:02:27,900 basehttp 214 138573560260288 "GET /admin/patients/visit/ HTTP/1.1" 200 13501
INFO 2025-07-25 12:02:27,931 basehttp 214 138573560260288 "GET /admin/jsi18n/ HTTP/1.1" 200 8717
WARNING 2025-07-25 12:11:21,465 log 214 138573560260288 Not Found: /wizyty/17/
WARNING 2025-07-25 12:11:21,466 basehttp 214 138573560260288 "GET /wizyty/17/?from=visits_list HTTP/1.1" 404 2682
ERROR 2025-07-25 12:36:48,027 log 214 138573526869696 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 12:36:48,034 basehttp 214 138573526869696 "GET /score2/stats/ HTTP/1.1" 500 271968
WARNING 2025-07-25 12:36:53,568 log 214 138573526869696 Not Found: /patients/1763/
WARNING 2025-07-25 12:36:53,569 basehttp 214 138573526869696 "GET /patients/1763/ HTTP/1.1" 404 3362
INFO 2025-07-25 12:37:00,645 basehttp 214 138573526869696 "GET /patients/ HTTP/1.1" 200 24343
ERROR 2025-07-25 12:37:27,003 log 214 138573526869696 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 12:37:27,008 basehttp 214 138573526869696 "GET /score2/stats/ HTTP/1.1" 500 271968
INFO 2025-07-25 12:39:17,020 basehttp 214 138573526869696 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 12:39:18,532 basehttp 214 138573526869696 "GET /patients/ HTTP/1.1" 200 24343
ERROR 2025-07-25 12:55:27,369 log 214 138573526869696 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 12:55:27,375 basehttp 214 138573526869696 "GET /score2/stats/ HTTP/1.1" 500 271968
ERROR 2025-07-25 13:11:53,141 log 214 138573560260288 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 623, in get
    return render(request, 'score2/stats.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
ERROR 2025-07-25 13:11:53,147 basehttp 214 138573560260288 "GET /score2/stats/ HTTP/1.1" 500 271968
INFO 2025-07-25 13:12:13,779 basehttp 214 138573560260288 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 13:12:15,562 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 13:12:16,215 basehttp 214 138573560260288 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 13:12:32,169 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 13:12:54,797 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 13:13:29,515 basehttp 214 138573526869696 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 13:13:38,801 basehttp 214 138573526869696 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 13:14:20,863 basehttp 214 138573526869696 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 13:14:26,868 basehttp 214 138573526869696 "GET /patients/?search=&diabetes=yes&age=40-49&score_status= HTTP/1.1" 200 24359
INFO 2025-07-25 13:14:31,574 basehttp 214 138573526869696 "GET /patients/?search=&diabetes=yes&age=&score_status= HTTP/1.1" 200 24351
INFO 2025-07-25 13:14:35,454 basehttp 214 138573526869696 "GET /patients/?search=&diabetes=&age=&score_status= HTTP/1.1" 200 24343
INFO 2025-07-25 13:29:15,241 basehttp 214 138573560260288 "GET /patients/ HTTP/1.1" 200 24343
INFO 2025-07-25 14:06:10,832 autoreload 214 138574248217472 /app/patients/models.py changed, reloading.
INFO 2025-07-25 14:06:12,032 autoreload 263 127745482783616 Watching for file changes with StatReloader
INFO 2025-07-25 14:07:31,458 autoreload 263 127745482783616 /app/score2/models.py changed, reloading.
INFO 2025-07-25 14:07:32,037 autoreload 276 123666833996672 Watching for file changes with StatReloader
INFO 2025-07-25 14:12:02,777 autoreload 276 123666833996672 /app/patients/views.py changed, reloading.
INFO 2025-07-25 14:12:03,282 autoreload 289 139325100112768 Watching for file changes with StatReloader
INFO 2025-07-25 14:12:46,036 autoreload 289 139325100112768 /app/patients/views.py changed, reloading.
INFO 2025-07-25 14:12:46,510 autoreload 302 132423547550592 Watching for file changes with StatReloader
INFO 2025-07-25 14:15:41,306 autoreload 302 132423547550592 /app/patients/views.py changed, reloading.
INFO 2025-07-25 14:15:41,810 autoreload 315 137906863991680 Watching for file changes with StatReloader
INFO 2025-07-25 14:17:06,679 autoreload 315 137906863991680 /app/score2/views.py changed, reloading.
INFO 2025-07-25 14:17:07,252 autoreload 328 128368336984960 Watching for file changes with StatReloader
INFO 2025-07-25 14:17:20,986 autoreload 328 128368336984960 /app/patients/forms.py changed, reloading.
INFO 2025-07-25 14:17:21,497 autoreload 341 132983840025472 Watching for file changes with StatReloader
ERROR 2025-07-25 14:17:26,301 log 341 132983150134976 Internal Server Error: /patients/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column patients.smoking_status does not exist
LINE 1: ...t" AS "col9", "patients"."updated_at" AS "col10", "patients"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/patients/views.py", line 136, in get_context_data
    patients_with_visits = eligible_patients.filter(visits__isnull=False).distinct().count()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column patients.smoking_status does not exist
LINE 1: ...t" AS "col9", "patients"."updated_at" AS "col10", "patients"...
                                                             ^

ERROR 2025-07-25 14:17:26,311 basehttp 341 132983150134976 "GET /patients/ HTTP/1.1" 500 142106
INFO 2025-07-25 14:18:00,151 basehttp 341 132983150134976 "GET /patients/ HTTP/1.1" 200 24343
ERROR 2025-07-25 14:18:05,589 log 341 132983150134976 Internal Server Error: /score2/stats/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/score2/views.py", line 594, in get
    min_date = today - relativedelta(years=90)
                       ^^^^^^^^^^^^^
NameError: name 'relativedelta' is not defined
ERROR 2025-07-25 14:18:05,600 basehttp 341 132983150134976 "GET /score2/stats/ HTTP/1.1" 500 70016
INFO 2025-07-25 14:18:11,638 basehttp 341 132983150134976 "GET /patients/import/ HTTP/1.1" 200 30551
INFO 2025-07-25 14:18:43,748 basehttp 341 132983150134976 "POST /patients/import/ HTTP/1.1" 302 0
INFO 2025-07-25 14:18:43,777 basehttp 341 132983150134976 "GET /patients/ HTTP/1.1" 200 25449
INFO 2025-07-25 14:18:45,816 basehttp 341 132983150134976 "GET /patients/ HTTP/1.1" 200 24343
